//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagementSystem.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.Educations = new HashSet<Education>();
        }
    
        public int ActivityID { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter ActivityName !")]
        [StringLength(maximumLength: 60, MinimumLength = 5, ErrorMessage = "Activity name must be from 5 to 60 charaters")]
        [DisplayName("Activity Name")]
        public string ActivityName { get; set; }

        [Required(ErrorMessage = "Please enter Description !")]
        [StringLength(maximumLength: 200, MinimumLength = 5, ErrorMessage = "Description must be from 5 to 200 charaters")]
        public string Description { get; set; }

    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Education> Educations { get; set; }
    }
}
