//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagementSystem.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClinicSystemData : DbContext
    {
        public ClinicSystemData()
            : base("name=ClinicSystemData")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<EducationFeedback> EducationFeedbacks { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Medicine> Medicines { get; set; }
        public virtual DbSet<MedicineFeedback> MedicineFeedbacks { get; set; }
        public virtual DbSet<MedicineImage> MedicineImages { get; set; }
        public virtual DbSet<MedicineOrderDetail> MedicineOrderDetails { get; set; }
        public virtual DbSet<MedicineType> MedicineTypes { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<ScientificApparatu> ScientificApparatus { get; set; }
        public virtual DbSet<ScientificApparatusFeedback> ScientificApparatusFeedbacks { get; set; }
        public virtual DbSet<ScientificApparatusImage> ScientificApparatusImages { get; set; }
        public virtual DbSet<ScientificApparatusOrderDetail> ScientificApparatusOrderDetails { get; set; }
        public virtual DbSet<ScientificApparatusType> ScientificApparatusTypes { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
