//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagementSystem.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Education()
        {
            this.EducationFeedbacks = new HashSet<EducationFeedback>();
        }
    
        public int EducationID { get; set; }
        public string LessonName { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Content { get; set; }
        public string Thumbnail { get; set; }
    
        public virtual Activity Activity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EducationFeedback> EducationFeedbacks { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
