//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagementSystem.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Employee
    {
        public string Username { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter password!")]
        [StringLength(maximumLength: 200, MinimumLength = 8, ErrorMessage = "Password must be from 8 to 200 charaters")]
        public string Password { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter fullname!")]
        [StringLength(maximumLength: 60, MinimumLength = 3, ErrorMessage = "Fullname must be from 3 to 60 charaters")]
        public string FullName { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please select date of birth")]
        [DataType(DataType.Date, ErrorMessage = "Birthdate must be date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DisplayName("Birthday")]
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<bool> Gender { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter phone number!")]
        [StringLength(maximumLength: 20, MinimumLength = 3, ErrorMessage = "Phone number must be from 3 to 20 charaters")]
        public string Phone { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter email!")]
        [StringLength(maximumLength: 60, MinimumLength = 6, ErrorMessage = "Email must be from 6 to 60 charaters")]
        public string Email { get; set; }
        public string Address { get; set; }
        public string Avatar { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<bool> Status { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
