//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagementSystem.EF
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class MedicineImage
    {
        public int ImageID { get; set; }
        public string FileName { get; set; }
        public Nullable<int> MedicineID { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }


        public virtual Medicine Medicine { get; set; }
    }
}
