//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagementSystem.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicine()
        {
            this.MedicineFeedbacks = new HashSet<MedicineFeedback>();
            this.MedicineImages = new HashSet<MedicineImage>();
            this.MedicineOrderDetails = new HashSet<MedicineOrderDetail>();
        }
    
        public int MedicineID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string MedicineName { get; set; }
        public string ShortDescription { get; set; }
        public string Composition { get; set; }
        public string Usage { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> OldUnitPrice { get; set; }
        public Nullable<int> UnitPrice { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual MedicineType MedicineType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicineFeedback> MedicineFeedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicineImage> MedicineImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicineOrderDetail> MedicineOrderDetails { get; set; }
    }
}
