//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagementSystem.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class MedicineType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicineType()
        {
            this.Medicines = new HashSet<Medicine>();
        }

        public int TypeID { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter TypeName !")]
        [StringLength(maximumLength: 60, MinimumLength = 5, ErrorMessage = "Medicine type name must be from 5 to 60 charaters")]
        [DisplayName("Type Name")]
        public string TypeName { get; set; }

        [Required(ErrorMessage = "Please enter Description !")]
        [StringLength(maximumLength: 200, MinimumLength = 5, ErrorMessage = "Description must be from 5 to 200 charaters")]
        public string Description { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicine> Medicines { get; set; }
    }
}
