//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagementSystem.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.MedicineOrders = new HashSet<MedicineOrder>();
            this.ScientificApparatusOrders = new HashSet<ScientificApparatusOrder>();
        }
    
        public int PaymentID { get; set; }

        [DisplayName("Payment Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter payment name !")]
        [StringLength(maximumLength: 60, MinimumLength = 5, ErrorMessage = "Payment name must be from 5 to 60 charaters")]
        public string PaymentName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicineOrder> MedicineOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScientificApparatusOrder> ScientificApparatusOrders { get; set; }
    }
}
