//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagementSystem.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScientificApparatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScientificApparatu()
        {
            this.ScientificApparatusOrderDetails = new HashSet<ScientificApparatusOrderDetail>();
            this.ScientificApparatusImages = new HashSet<ScientificApparatusImage>();
            this.ScientificApparatusFeedbacks = new HashSet<ScientificApparatusFeedback>();
        }
    
        public int ScientificApparatusID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string ScientificApparatusName { get; set; }
        public string ShortDescription { get; set; }
        public string Composition { get; set; }
        public string Usage { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> OldUnitPrice { get; set; }
        public Nullable<int> UnitPrice { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScientificApparatusOrderDetail> ScientificApparatusOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScientificApparatusImage> ScientificApparatusImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScientificApparatusFeedback> ScientificApparatusFeedbacks { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ScientificApparatusType ScientificApparatusType { get; set; }
    }
}
