//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagementSystem.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ScientificApparatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScientificApparatu()
        {
            this.ScientificApparatusOrderDetails = new HashSet<ScientificApparatusOrderDetail>();
            this.ScientificApparatusImages = new HashSet<ScientificApparatusImage>();
            this.ScientificApparatusFeedbacks = new HashSet<ScientificApparatusFeedback>();
        }
    
        public int ScientificApparatusID { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please choice scientific apparatus type!")]
        public Nullable<int> TypeID { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please choice supplier !")]
        public Nullable<int> SupplierID { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter scientific apparatus name !")]
        [StringLength(maximumLength: 100, MinimumLength = 5, ErrorMessage = "Scientific apparatus Name must be between 5 to 100 charaters.")]
        [DisplayName("Scientific Apparatus Name")]
        public string ScientificApparatusName { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter short description!")]
        [StringLength(maximumLength: 200, MinimumLength = 5, ErrorMessage = "Short description must be between 5 to 200 charaters.")]
        [DisplayName("Short Description")]
        public string ShortDescription { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter description!")]
        public string Description { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter specification!")]
        public string Specification { get; set; }

        [DisplayName("Unit In Stock")]
        [Range(maximum: Int64.MaxValue, minimum: 0, ErrorMessage = "Unit in stock must be a positive number")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter unit in stock!")]
        public Nullable<int> UnitInStock { get; set; }

        [DisplayName("Unit On Order")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter unit on order!")]
        [Range(maximum: Int64.MaxValue, minimum: 0, ErrorMessage = "Unit On Order must be a positive number")]
        public Nullable<int> UnitOnOrder { get; set; }

        [DisplayName("Old Unit Price")]
        [Range(maximum: Int64.MaxValue, minimum: 0, ErrorMessage = "Old unit price must be a positive number")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter old unit price!")]
        public Nullable<int> OldUnitPrice { get; set; }

        [DisplayName("Unit Price")]
        [Range(maximum: Int64.MaxValue, minimum: 0, ErrorMessage = "Unit price must be a positive number")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter unit price!")]
        public Nullable<int> UnitPrice { get; set; }

        public string Thumbnail { get; set; }

        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScientificApparatusOrderDetail> ScientificApparatusOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScientificApparatusImage> ScientificApparatusImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScientificApparatusFeedback> ScientificApparatusFeedbacks { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ScientificApparatusType ScientificApparatusType { get; set; }
    }
}