//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagementSystem.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScientificApparatusOrderDetail
    {
        public int OrderID { get; set; }
        public int ScientificApparatusID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual ScientificApparatu ScientificApparatu { get; set; }
        public virtual ScientificApparatusOrder ScientificApparatusOrder { get; set; }
    }
}
