//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagementSystem.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ScientificApparatusType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScientificApparatusType()
        {
            this.ScientificApparatus = new HashSet<ScientificApparatu>();
        }
    
        public int TypeID { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter medicine type name !")]
        [StringLength(maximumLength: 60, MinimumLength = 5, ErrorMessage = "Scientific apparatus type name must be from 5 to 60 charaters")]
        [DisplayName("Type Name")]
        public string TypeName { get; set; }

        [Required(ErrorMessage = "Please enter Description !")]
        [StringLength(maximumLength: 200, MinimumLength = 5, ErrorMessage = "Description must be from 5 to 200 charaters")]
        public string Description { get; set; }
    

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScientificApparatu> ScientificApparatus { get; set; }
    }
}
