//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagementSystem.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.Medicines = new HashSet<Medicine>();
            this.ScientificApparatus = new HashSet<ScientificApparatu>();
        }

        
        public int SupplierID { get; set; }

        [DisplayName("Company Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter Company Name !")]
        [StringLength(maximumLength: 60, MinimumLength = 5, ErrorMessage = "Company name must be from 5 to 60 charaters")]
        public string CompanyName { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter Contact Name !")]
        [StringLength(maximumLength: 60, MinimumLength = 5, ErrorMessage = "Contact name must be from 5 to 60 charaters")]
        [DisplayName("Contact Name")]
        public string ContactName { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter Address !")]
        [StringLength(maximumLength: 200, MinimumLength = 5, ErrorMessage = "Address must be from 5 to 200 charaters")]
        public string Address { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter Phone Number !")]
        [RegularExpression(@"^[+]*[(]{0,1}[0-9]{1,4}[)]{0,1}[-\s\./0-9]*$", ErrorMessage = "Incorrect phone number format !")]
        [StringLength(maximumLength: 10, MinimumLength = 3, ErrorMessage = "Phone number must be from 3 to 10 charaters")]
        public string Phone { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter Email !")]
        [RegularExpression(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$", ErrorMessage = "Incorrect email format !")]
        [StringLength(maximumLength: 50, MinimumLength = 6, ErrorMessage = "Email must be from 3 to 10 charaters")]
        public string Email { get; set; }
        

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicine> Medicines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScientificApparatu> ScientificApparatus { get; set; }
    }
}
